Include string.h
memcmp, memset, etc. are declared in string.h. Make sure to include this
header. Put it in project.h like is done for all other includes.

Fixes the following error on recent GCC:

src/logic.c:119:51: error: implicit declaration of function ‘memcmp’ [-Werror=implicit-function-declaration]
  119 |                         } else if(recvLen == 4 && memcmp(rxBuf, "KICK", 4) == 0) {
      |                                                   ^~~~~~
src/logic.c:29:1: note: include ‘<string.h>’ or provide a declaration of ‘memcmp’
   28 | #include "project.h"
  +++ |+#include <string.h>
   29 |